'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# we need the first numbers of our sequence
a = 0
b = 1
res = 0

# we need to create the cycle & go through the sequence
# in order to find the sum of even terms
while b < 4000000:
    temp = a
    a = b
    b = temp + a
    if b % 2 == 0: res += b

print(res)
